name: LCCAD
options:
  bundleIdPrefix: co.whatever
  deploymentTarget:
    macOS: "14.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  LCCAD:
    type: application
    platform: macOS
    sources:
      - Sources/LCCAD
    resources:
      - path: Sources/LCCAD/Resources
        excludes:
          - Info.plist
          - LCCAD.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: co.whatever.LCCAD
        PRODUCT_NAME: LCCAD
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: Sources/LCCAD/Resources/Info.plist
        ENABLE_PREVIEWS: true
        DEVELOPMENT_TEAM: G5G54TCH8W
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: Sources/LCCAD/Resources/LCCAD.entitlements
    scheme:
      testTargets:
        - LCCADTests

  LCCADTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - Tests/LCCADTests
    dependencies:
      - target: LCCAD
    settings:
      base:
        BUNDLE_LOADER: $(TEST_HOST)
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/LCCAD.app/Contents/MacOS/LCCAD
        GENERATE_INFOPLIST_FILE: true
        DEVELOPMENT_TEAM: G5G54TCH8W
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
